<?php Css::add('portada'); ?>

<div class="bg">
    <img class="computer s0 m0" src="/img/mansion.computer.png">
    <img class="tablet s0 l0" src="/img/mansion.tablet.png">
    <img class="mobile m0 l0" src="/img/mansion.mobile.png">
</div>

<div class="col s12">
	<?=Caja::progreso('Progreso general de la APP', 70)?>
</div>

<div class="col s12 m6 l4">
	<?=Caja::progreso('Formulario de acceso', 100)?>
	<?=Caja::progreso('Cantidad de fichas', 80)?>
	<?=Caja::progreso('Cantidad de losetas', 90)?>
	<?=Caja::progreso('Orden de rotacion en losetas', 50)?>
	<?=Caja::progreso('Filtro de losetas por set', 0)?>
</div>

<div class="col s12 m6 l4">
	<?=Caja::progreso('Progreso del editor', 90)?>
	<?=Caja::progreso('Formulario de escenario', 90)?>
	<?=Caja::progreso('Rejilla de losetas', 100)?>
	<?=Caja::progreso('Formulario de elementos con audio', 100)?>
	<?=Caja::progreso('Establecer IA', 0)?>
	<?=Caja::progreso('Botón salir', 100)?>
</div>

<div class="col s12 m6 l4">
	<?=Caja::progreso('Progreso de la parte interactiva', 80)?>
	<?=Caja::progreso('Portada', 100)?>
	<?=Caja::progreso('Listado de escenarios con filtro', 100)?>
	<?=Caja::progreso('Filtro de escenarios por set', 0)?>
	<?=Caja::progreso('Listado de personajes con filtro', 100)?>
	<?=Caja::progreso('Hasta 6 investigadores', 100)?>
	<?=Caja::progreso('Objetos al azar y pistas', 80)?>
	<?=Caja::progreso('Introducción', 100)?>
	<?=Caja::progreso('Rejilla', 100)?>
	<?=Caja::progreso('Primera escena', 100)?>
	<?=Caja::progreso('Ventanas de elementos con audio', 100)?>
	<?=Caja::progreso('Botón descubrir', 100)?>
	<?=Caja::progreso('Botón de opciones', 80)?>
	<?=Caja::progreso('Opción historial de mensajes', 100)?>
	<?=Caja::progreso('Opción activar fuego', 0)?>
	<?=Caja::progreso('Opción investigador eliminado', 0)?>
	<?=Caja::progreso('Botón de monstruos', 0)?>
	<?=Caja::progreso('Botón de objetos', 0)?>
	<?=Caja::progreso('Botón cambio de fase', 0)?>
	<?=Caja::progreso('Aplicar IA', 0)?>
	<?=Caja::progreso('Botón salir', 100)?>
	<div class="clearfix"></div>
</div>
