
<ul class="ml20">
	<li class="ph0">
		KuDB v<?=$version?> (Base de datos: <?=$database?>)
		<ul>
			<li>
				<i class="material-icons">subdirectory_arrow_right</i>
				Creación de tablas.
				<ul class="ml20">
					<li>
						<i class="material-icons">subdirectory_arrow_right</i>
						Creación de columnas y sus propiedades.
					</li>
					<li>
						<i class="material-icons">subdirectory_arrow_right</i>
						Listado de columnas con sus propiedades.
						<ul class="ml20">
							<li>
								<i class="material-icons">subdirectory_arrow_right</i>
								Filtro caliente de las tablas mostradas.
							</li>
						</ul>
					</li>
					<li>
						<i class="material-icons">subdirectory_arrow_right</i>
						Actualización de columnas y sus propiedades.
					</li>
					<li>
						<i class="material-icons">subdirectory_arrow_right</i>
						Eliminación de columnas.
					</li>
				</ul>
				<ul class="ml20">
					<li>
						<i class="material-icons">subdirectory_arrow_right</i>
						Creación de filas y sus valores.
					</li>
					<li>
						<i class="material-icons">subdirectory_arrow_right</i>
						Listado de filas con sus valores.
						<ul class="ml20">
							<li>
								<i class="material-icons">subdirectory_arrow_right</i>
								Busqueda de contenido por campo.
							</li>
							<li>
								<i class="material-icons">subdirectory_arrow_right</i>
								Ordenación por campo, sentido y número de filas por página.
							</li>
							<li>
								<i class="material-icons">subdirectory_arrow_right</i>
								Filtro caliente de las filas mostradas.
							</li>
							<li>
								<i class="material-icons">subdirectory_arrow_right</i>
								Paginación.
							</li>
						</ul>
					</li>
					<li>
						<i class="material-icons">subdirectory_arrow_right</i>
						Actualización de filas y sus valores.
					</li>
					<li>
						<i class="material-icons">subdirectory_arrow_right</i>
						Eliminación de filas.
					</li>
				</ul>
			</li>
			<li>
				<i class="material-icons">subdirectory_arrow_right</i>
				<a data-toggle="aside, #sidenav-overlay">Listado de tablas de la base de datos seleccionada.</a>
			</li>
			<li>
				<i class="material-icons">subdirectory_arrow_right</i>
				Renombrado de tablas.
			</li>
			<li>
				<i class="material-icons">subdirectory_arrow_right</i>
				Eliminación de tablas.
			</li>
		</ul>
	</li>
</ul>
