
<form action class="col s12" method="post">
    <ul class="collection">
        <li class="collection-item ph0">
            <h1 class="col s12">
                Tabla <?=($table)?"\"$table\"":'nueva'?>
                <a href="/admin/kudb/table/<?=$table?>">
                    <sup><i class="small material-icons">edit</i></sup>
                </a>
            </h1>
            <h2 class="col s12">
                Registro <?=($row)?"\"$row->id\"":'nuevo'?>
                <a href="/admin/kudb/row/<?=$table?>">
                    <i class="small material-icons">add</i>
                </a>
            </h2>
            <div class="clearfix"></div>
        </li>
        <li class="collection-item" style="overflow-x:auto">
            <?php include APP_PATH . 'views/admin/kudb/form.phtml'; ?>
        </li>
        <li class="collection-item pt0">
            <div class="col s12 m3 l3 mt10">
                <button type="submit" class="all-width btn green darken-1" name="action" value="create_row">Crear registro</button>
            </div>
            <?php if ( ! empty($row) ) : ?>
                <div class="col s12 m3 l3 mt10">
                    <button type="submit" class="all-width btn orange darken-1" name="action" value="update_row">Actualizar registro</button>
                </div>
                <div class="col s12 m3 l3 delete_row mt10">
                    <button type="button" class="all-width btn red darken-1" data-toggle=".delete_row button">Eliminar registro</button>
                    <button type="submit" class="all-width btn red darken-1" name="action" style="display:none" value="delete_row"><?=_('¿Seguro?')?></button>
                </div>
                <input type="hidden" name="id" value="<?=$row->id?>">
            <?php endif; ?>
            <div class="clearfix"></div>
        </li>
    </ul>
    <input type="hidden" name="table" value="<?=$table?>">
</form>
