
<ul class="center-align collection grey-text text-lighten-2"> 
	<li class="black collection-item">
		¿Con que tipo de arma vas a atacar?
	</li> 
	<li class="black box-link collection-item">
		<img src="/img/action.png"> Atacar con un arma pesada
		<a data-ajax=".modal.attacks" href="/registrados/pnjs/usar/arma_pesada/<?=$pnj->id?>/"></a>
	</li>  
	<li class="black box-link collection-item">
		<img src="/img/action.png"> Atacar con un arma de filo
		<a data-ajax=".modal.attacks" href="/registrados/pnjs/usar/arma_de_filo/<?=$pnj->id?>/"></a>
	</li>  
	<li class="black box-link collection-item">
		<img src="/img/action.png"> Atacar con un arma de fuego
		<a data-ajax=".modal.attacks" href="/registrados/pnjs/usar/arma_de_fuego/<?=$pnj->id?>/"></a>
	</li>  
	<li class="black box-link collection-item">
		<img src="/img/action.png"> Atacar con un hechizo
		<a data-ajax=".modal.attacks" href="/registrados/pnjs/usar/hechizo/<?=$pnj->id?>/"></a>
	</li>  
	<li class="black box-link collection-item">
		<img src="/img/action.png"> Atacar sin arma
		<a data-ajax=".modal.attacks" href="/registrados/pnjs/usar/sin_arma/<?=$pnj->id?>/"></a>
	</li>  
	<li class="black box-link collection-item">
		Cancelar
		<a data-close=".modal.attacks"></a>
	</li>  
</ul>
