
<ul class="center-align collection grey-text text-lighten-2"> 
	<li class="black collection-item">
		Entrar o salir del área de acción de un monstruo sin recibir castigo es siempre algo arriesgado, ¿estás seguro?
	</li> 
	<li class="black box-link collection-item">
		<img src="/img/action.png"> Esquivar a la criatura
		<a data-ajax=".modal.escape" href="/registrados/pnjs/hacer/esquiva/<?=$pnj->id?>/"></a>
	</li>  
	<li class="black box-link collection-item">
		Cancelar
		<a data-close=".modal.escape"></a>
	</li>  
</ul>
