<!DOCTYPE HTML>
<html lang="es" id="important">
	<head>
		<meta charset="utf-8">
		<title>KuDB</title>
		<link href="/css/materialize.min.css" rel="stylesheet">
		<link href="/css/material-icons.css" rel="stylesheet">
		<link href="/css/hacks.css" rel="stylesheet">
		<link href="/css/helpers.css" rel="stylesheet">
		<link href="/css/admin/kudb/style.css" rel="stylesheet">
		<link href="/css/admin/kudb/nav.css" rel="stylesheet">
		<?=Css::inc()?>
	</head>
	<body class="row">
		<?php View::partial('kudb/nav'); ?>
		<?php View::partial('kudb/aside'); ?>
		<?php View::content(); ?>

		<div id="ajax-container"></div>
        <div id="sidenav-overlay"></div>

		<script src="/javascript/jquery/jquery-3.1.1.min.js"></script>
		<script src="/javascript/materialize.min.js"></script>
		<script src="/javascript/function.js"></script>
		<script src="/javascript/script.js"></script>
		<script src="/javascript/filter.js"></script>
		<script>
			function triggers()
			{

			}	

			$(function()
			{
				triggers();

			});
		</script>
		
        <?php View::partial('toast'); ?>
	</body>
</html>