SET NAMES utf8;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `mitos`;

CREATE TABLE `mitos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `usuarios_id` int(11) DEFAULT NULL,
  `escenarios_id` int(11) DEFAULT NULL,
  `turno` smallint(111) DEFAULT NULL,
  `texto` text,
  `voz` varchar(111) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=96 DEFAULT CHARSET=utf8;

insert into `mitos` values('3','5','10','1','LOL','laugh_bugs.mp3'),
 ('2','5','10','2','Texto para la fase de mitos.','laugh_bugs.mp3'),
 ('6','246','43','1','Comenzáis a sentir que la vida en ese lugar no era tal y como os la habían contado.',''),
 ('7','246','43','2','Queréis registrar toda la propiedad, no vaya a ser que se os escape algo.',''),
 ('8','246','43','3','Ya estáis dando por finalizada vuestra inspección.',''),
 ('9','246','43','4','Deberíais ir marchándoos.',''),
 ('10','246','43','5','Dais por finalizada vuestra investigación y os dirigís a abandonar la propiedad.',''),
 ('12','246','65','1','La casa esconde más secretos de los que parece',''),
 ('13','246','65','2','Os empezáis a hacer con la distribución de la morada',''),
 ('14','246','65','3','Va siendo hora de terminar el trabajo',''),
 ('15','246','65','4','Hay que abandonar el lugar de inmediato',''),
 ('16','295','72','1','Este evento de la fase de mitos afecta a todos los jugadores en una loseta de escenario interior.\r\n\r\nEmpiezas a sentir un sentimiento de claustrofobia como nunca antes habías tenido en tu vida. Comienzas a temer por tu integridad física e intentas buscar una ventana a la desesperada para respirar aire fresco.\r\n\r\nSin efectos inmediatos','mito1.wav'),
 ('17','295','72','2','Este evento de los mitos afecta a todos los jugadores.\r\n\r\nSientes que el veneno ataca de nuevo y vuelves a caer al suelo. Recibes una carta de herida boca arriba (anulada por FUERZA)','mito2.wav'),
 ('18','295','72','3','Este evento de los mitos afecta al jugador con menos SABER\r\n\r\nTe sientes desconcertado al sentirte muy lejos de casa y tus ideas más ocultas y oscuras se apresan de ti.\r\n\r\nRecibes dos cartas de horror boca abajo, anuladas por SABER\r\n\r\n','mito3.wav'),
 ('19','295','72','4','Este evento de los mitos afecta al jugador con menos fuerza.\r\n\r\nSientes un dolor lacerante en tu brazo izquierdo, miras y parece que hay algo que intenta salir de ti. Clavas tu navaja multiusos sobre la piel, lacerándola.\r\n\r\nRecibes dos cartas de herida (anuladas por voluntad)','mito4.wav'),
 ('20','295','72','5','Este evento afecta a todos los jugadores que estén en una carta de pasillo o en una habitación de menos de dos casillas.\r\n\r\nSientes como las paredes y el techo cae sobre ti y crees que no puedes escapar, creyendo que tu final es inevitable. Recibes dos cartas de horror (anuladas por VOLUNTAD)','mito5.wav'),
 ('21','295','72','6','Este evento afecta a todos los jugadores.\r\n\r\nTe pesan las piernas y sientes un dolor en el estómago que nunca habías experimentado.\r\n\r\nHaces un alto en el camino y te apoyas contra la pared más cercana para vomitar. Te abruma haberlo hecho en el hotel, pero ya sentías cómo corría la bilis por tu estófago.\r\n\r\nCrees que has expulsado todo el veneno que te suministraron.\r\n\r\nCada jugador puede descartar una carta de herida boca abajo o poner una carta de herida que esté boca arriba boca abajo.','mito6.wav'),
 ('22','295','72','7','Este evento de los mitos afecta a todos los jugadores.\r\n\r\nRespiras fuerte y notas una brisa marina que te trae amargos recuerdos.\r\n\r\nA tu mente vienen recuerdos de tu infancia cuando tu padre murió ahogado mientras se bañaba en la playa, aunque, a decir verdad, se lo mereció al atreverse a meterse en el mar después de cuatro whiskeys durante el temporal.\r\n\r\nSi superas una tirada de VOLUNTAD (2 éxitos) consigues superar tu trauma y puedes quitarte una carta de horror boca abajo o volver una boca arriba, boca abajo.\r\n\r\nSi fallas recibe una carta de horror boca arriba y otra boca abajo.','mito7.wav'),
 ('23','295','72','8','Este evento de los mitos afecta al jugador con menos OBSERVACIÓN.\r\n\r\nEl cansancio se apodera de ti y se aparece ante ti el espíritu del padre Winston, el cura de tu colegio que abusaba de ti.\r\n\r\nIntentas que el espíritu se marche, ya que no puedes hacer frente a tu visión.\r\n\r\nHaz una tirada de NEGOCIACIÓN (2 éxitos) Si la superas, el espectro se desvanece. Si no, tus secretos más enterrados vuelven a ti y recibes dos cartas de horror.','mito8.wav'),
 ('24','295','72','9','Este afecto de los mitos afecta a todos los jugadores.\r\n\r\nPoco a poco vas recobrando tus recuerdos. Ya sabes que estás en Kingston, lejos de casa vienen a la mente ciertos recuerdos de ayer.\r\n\r\nRecuerdas haber estado en un bar celebrando tu día de paga, ya que ves una herida en tu costado que recibiste en una pelea con un borracho.\r\n\r\nIntentas remendar tu herida con lo que tienes a mano. Recibes 2 cartas de herida boca abajo, anuladas por una tirada de SABER.','mito9.wav'),
 ('25','295','72','10','Este efecto de los mitos afecta a todos los jugadores que estén en una ficha de escenario interior.\r\n\r\nRecuerdas que si bien eras mucho más fuerte que el borracho con el que peleaste, sacó una daga emponzoñada de un líquido viscoso que a buen seguro era tóxico, acertando a clavártela en el costado y provocándote la herida que antes emanaba sangre.\r\n\r\nTe frustras por no poder recordar más.\r\n\r\nGanas una carta de herida y una carta de horror, anuladas por VOLUNTAD.','mito10.wav'),
 ('26','295','72','11','Sientes que tu cordura está llegando a sus límites tras las abominaciones que estás presenciando durante las últimas horas.\r\n\r\nEl jugador que más cartas de horror haya recibido durante el juego, recibe una carta de horror, anulada por VOLUNTAD (-1)','mito11.wav'),
 ('27','295','72','12','Este evento de la fase de mitos afecta a todos los jugadores.\r\n\r\nNo por conocida, la visión deja de ser menos alentadora. Llevas más de quince años teniendo esta pesadilla recurrente, desde que asististe al sepelio de tu abuelo.\r\n\r\nMás que la propia muerte, te atormenta tu apellido grabado en piedra en el panteón familiar, recordándote no solo que el final nos llega a todos, sino que, en tu caso, el lugar del descanso eterno ya está definido.\r\n\r\nEstás más que acostumbrado a esta pesadilla, solo que ahora estás despierto ...\r\n\r\nSin efectos inmediatos','mito12.wav'),
 ('28','295','72','13','Este evento de la fase de mitos afecta solamente a los jugadores en losetas de escenario interior.\r\n\r\nTe miras ante un espejo y te horrorizas al ver la imagen de ti mismo frente al espejo. Lo que ves ante ti te horroriza y no crees lo que estás viendo reflectado: los dientes de tu boca se han caído y tienes las cuencas de los ojos vacías.\r\n\r\nRealiza una tirada de Fuerza (dificultad 2):\r\n\r\n-Si aciertas: pegas un puñetazo al espejo y la imagen fantasmagórica desaparece.\r\n\r\n-Si fallas: recibe una carta de horror.','mito13.wav'),
 ('29','295','72','14','Sufres una crisis existencial y te planteas si la vida de investigador merece la pena: el sueldo es inestable y contemplas horrores de otras galaxias que pocos han visto y que te perturban en tus pesadillas.\r\n\r\nRealiza una tirada de SABER, (dificultad: 1):\r\n\r\n-Si tienes éxito: Te reafirmas en tu decisión de seguir investigando, sabes que es lo mejor que sabes hacer en esta vida. Sin efecto.\r\n\r\n-Si fallas: la angustia vital te hace mutilarte con la hebilla de tu cinturón. Para aliviar el dolor mental, recurres a hacerte daño físico. Recibe 1 carta de herida boca arriba.','mito14.wav'),
 ('30','295','72','15','Sientes como la tierra retumba ante tus pies. Nunca has tenido una sensación igual a lo largo de tu vida y te preguntas si será el último día en el que verás la luz del Sol.\r\n\r\nSin efectos inmediatos.','mito15.wav'),
 ('31','295','72','16','Este evento de la fase de mitos afecta al jugador con menos NEGOCIACIÓN\r\n\r\nVes una mancha de sangre en el suelo y al acercarte percibes como una gota aún más roja cae sobre ella. Solo puede venir de un sitio: de tu boca.\r\n\r\nComienzas a toser sangre sin saber muy bien el porqué ¿el veneno ataca de nuevo? ¿cansancio? ¿enfermedad?\r\n\r\nRecibe dos cartas de horror anuladas por SABER','mito16.wav'),
 ('32','246','90','1','Os proponéis desvelar el misterio de esta casa',''),
 ('33','246','90','2','Comenzáis a adentraros en serio en el corazón de la morada',''),
 ('34','246','90','3','Empezáis a unir las piezas del rompecabezas',''),
 ('35','246','90','4','La solución está al alcance de vuestros dedos',''),
 ('36','246','90','5','Ha llegado el momento de arriesgar; vencer o morir',''),
 ('37','246','90','6','Al fin, sentís que la investigación ha llegado a su fin',''),
 ('38','246','90','7','La mansión del músico cierra de nuevo sus puertas, y esta vez, puede que para siempre',''),
 ('39','295','72','17','Miras al sol y por su altura deduces que llevas ya 17 horas intentando salir de Kingston, el tiempo juega en tu contra y sabes, de sobra, que tienes que escoger la opción más segura para dejar esta ciudad maldita para siempre.\r\n\r\nTodos los jugadores reciben una carta de horror (anulado por VOLUNTAD)','mito17.wav'),
 ('40','295','72','19','Este evento solo afecta a los jugadores que estén en losetas de escenario exterior.\r\n\r\nLa hija de los dueños del hotel ha dado la voz de alarma y te están buscando para llevarte a tu macabro destino. Todavía sacas unos metros a tus perseguidores, crees que puedes esquivar las piedras que te lanzan para intentar reducirte.\r\n\r\nRealiza una tirada de agilidad (dificultad:1) Si fallas, recibe una carta de herida boca abajo.','mito19.wav'),
 ('41','295','72','20','Este evento de la fase de mitos afecta al jugador con menos saber\r\n\r\nMiras a tus pies y ves cómo el suelo se abre lentamente, dejando entrever las fauces de un horror cósmico. No sabes si lo que ves es real o no, pero la visión te perturba hasta límites no conocidos por tu mente.\r\n\r\nRecibes una carta de horror boca arriba y otra boca abajo, anuladas por voluntad.','mitos20.wav'),
 ('42','328','101','1','muere',''),
 ('43','130','108','0','',''),
 ('45','5','44','10','Mala suerte chicos, la mansión tiembla hasta el punto que caéis al suelo. Veis como se abre una brecha cósmica frente a vosotros de donde salen unos gruesos tentáculos de color morado. Son tan rápidos que a penas podéis reaccionar. Atrapados por los tentáculos sois llevados a través de esa brecha cósmica que se cierra tras vosotros. En el más allá el cuerpo se destruye y la mente es torturada en un sufrimiento sin igual.','FIN.mp3'),
 ('46','5','118','20','Se acabó el mundo.',''),
 ('47','381','125','1','Prueba1',''),
 ('49','414','136','0','',''),
 ('53','246','151','1','Todo permanece tranquilo. No hay efecto inmediato.',''),
 ('54','246','151','2','Todos los investigadores que se encuentran en el salón empiezan a respirar profundamente la fragancia a lavanda, perdiéndose en sus recuerdos de la infancia. Ninguno quiere marcharse de allí, por lo que adquieren el estado Retenido.',''),
 ('55','246','151','3','Una vibración recorre el suelo de la casa y todos sus siniestros habitantes sonríen con malicia. Todos los monstruos heridos se curan de 2 daños.',''),
 ('56','246','151','4','Un eco retumba por la casa, sobresaltándoos. Todos los investigadores sufren 1 Horror bocabajo',''),
 ('57','246','151','5','La partida ha finalizado. Si ninguno de los investigadores posee los estados de Loco o Herido y no queda ningún monstruo con vida en la casa, los investigadores ganan la partida. En caso contrario, los investigadores pierden la partida.',''),
 ('58','414','154','1','el olor a muerto del cementerio se siente en todas las estancias de la zona precisamente no es de lo mas agradable pero un poco de brisa no vendria mal sin efecto para los investigadores. ','MITO1.mp3'),
 ('60','459','170','1','Llegais al hall de la mansion de Jack y os recive Walter, el mayordomo de Jack, con una cara seria y a la vez trsite en sus ojos, os mira seriamente y dando un respiro os dice -El señor les esta esperando en la sala de baile, por favor, vayan por la puerta de la iquierda y continuen el pasillo-',''),
 ('61','487','189','1','',''),
 ('62','487','193','1','Se oye un estruendo y el crujir de las maderas de la casa, un sonido de otro mundo que os aterra; los jugadores reciben 1 de horror boca abajo, anulados por Voluntad',''),
 ('64','520','208','0','Te despiertas en un baño con dolor de cabeza',''),
 ('66','551','219','1','El tiempo parece pasar más lento en algunas ocasiones, y más rápido en otras. \r\nNo hay ningún efecto. ',''),
 ('67','551','219','2','Las luces empiezan a fallar y surge una densa oscuridad que parece extenderse como si tuviera vida propia, bloqueando la entrada... y la salida. \r\nColoca una ficha de oscuridad en la escalera del pasillo. ',''),
 ('69','565','230','1','trwyertytrey',''),
 ('70','658','271','0','',''),
 ('75','682','287','1','Se escuchan gritos que os hacen estremecer todos los sentidos por lo que temblais de miedo: (Tirada de voluntad: 2) \r\nSi la supera no se comen ningún horror. Si no lo consiguen se comen 2 de horror boca abajo.',''),
 ('77','682','287','2','Cuando pensabais que estabais solos aparece por el pasillo alguien nada familiar, parece llevar una capucha. \r\n\r\nColocar sectario en el pasillo 2. Vida: la que tenga el sectario',''),
 ('78','701','305','0','',''),
 ('81','723','315','1','En estas calles huele a muerto. Sería bueno que os movieseis rápido',''),
 ('82','723','315','2','Una espesa bruma inunda las calles. Este efecto afecta los personajes que estén en un exterior. \r\n',''),
 ('83','729','319','5','uilki',''),
 ('84','719','311','1','en estas calles hace demasiado frio, no seria conveniente seguir al aire libre a estas horas',''),
 ('85','740','333','1','',''),
 ('86','740','333','0','',''),
 ('87','682','287','3','Voces susurrantes resuenan por los pasillos. (Investigador al azar) es insoportable el sonido. (I al Azar) sufre 1 de daño boca abajo y uno de horror anulados por voluntad',''),
 ('88','682','287','4','(Inv. Azar) se encuentra perdido/a entre las paredes de la residencia por lo que siente unas nauseas. Sufres 2 de horror anulados por observacion. ',''),
 ('89','682','287','5','La tension provocada por la investigacion os hace dudar de porque estais ahi metidos. Afecta al investigador que tenga menos Fuerza. Lanzar (voluntad, 2) si la superas consigues entender la situación en la que estas. Si fallas sufres 1 de horror y desconcertado',''),
 ('90','682','287','6','Parece que la residencia tiembla por lo que os estremeceis. Este evento afecta a todos los investigadores que se encuentren en un pasillo. Caen varias lamparas del techo: Sufres 2 de daño y desconcertado.',''),
 ('91','682','287','7','Una siniestro grito resuena entre las paredes de la residencia. Sentis estremecer vuestros sentidos. (I. Azar) Sufre dos de horror anulados por voluntad. Luego poner dos cartas de horror boca arriba. Aparece un sectario en la parcela 2',''),
 ('92','682','287','8','Investigador al aza: intenta coger un objeto pero este se rompe, por lo que tienes que descartar un objeto común ya que se ha quedado inservible.',''),
 ('93','682','287','9','Escuchas desde lejos un conjuro no sabes identificarlo, por lo que lo intentas descifrar: (saber, 2).  Si fallas la tirada sufres 3 de horror y adquieres el estado retenido.',''),
 ('94','682','287','10','La investigación parece que va llegando a su fin, os estais quedando sin fuerzas, cada investigador sufre 2 de daño. ',''),
 ('95','682','287','11','Os dais cuenta de que hay algo en la pared que no habiais percibido. Este evento de mitos afecta a cualquier investigador que se encuentre en cualquier pasillo.  Veis unos cuadros que cada vez se ven mas tenebrosos lo que os transmite inseguridad. Sufres dos de horror (anulados por voluntad).','');

SET FOREIGN_KEY_CHECKS = 1;
